ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080

koog:
  openai:
    apikey: <OPENAI_API_KEY>

langfuse:
  lfbase: https://cloud.langfuse.com
  lfpublic: <LANGFUSE_PUBLIC_KEY>
  lfsecret: <LANGFUSE_SECRET_KEY>

tavily:
  apikey: <TAVILY_API_KEY>
